# Generated by Django 2.0.3 on 2018-04-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0008_auto_20180401_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='pk_stops.Spot'),
        ),
    ]
