# Generated by Django 2.0.3 on 2018-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0011_auto_20180401_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_till_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
