# Generated by Django 2.0.3 on 2018-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0012_auto_20180401_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
