# Generated by Django 2.0.3 on 2018-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0013_auto_20180402_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
