# Generated by Django 2.0.3 on 2018-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0014_auto_20180402_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_from_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_till_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
