# Generated by Django 2.0.3 on 2018-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0015_auto_20180403_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
