# Generated by Django 2.0.3 on 2018-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_stops', '0017_auto_20180503_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exit',
            field=models.BooleanField(default=False),
        ),
    ]
